import content from '@/content/portfolio.json';
export type SiteSettings = typeof content.settings;
export type Profile = typeof content.profile;
export type Work = (typeof content.work)[number];
export type Experience = (typeof content.experience)[number];
export type Education = (typeof content.education)[number];
export type Portfolio = typeof content & { unavailable?: boolean };
export type Lab = {
  id: string;
  title: string;
  summary: string;
  url: string;
  topics: string[];
  language: string;
  updatedAt: string | null;
  kind: string;
  featured: boolean;
  learningNotes?: string;
  image?: string;
  imageAlt?: string;
  order?: number;
};
export type LabFeed = { labs: Lab[]; unavailable: boolean };
